import i18n from '@/i18n'

const { t } = i18n.global

export const enum KEYS {
  C = 'C',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  O = 'O',
  R = 'R',
  T = 'T',
  MINUS = '-',
  EQUAL = '=',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F6 = 'F6',
}

export const HOTKEY_DOC = [
  {
    type: t('ppt.hotkeyGeneral'),
    children: [
      { label: t('ppt.hotkeyCut'), value: 'Ctrl + X' },
      { label: t('ppt.hotkeyCopy'), value: 'Ctrl + C' },
      { label: t('ppt.hotkeyPaste'), value: 'Ctrl + V' },
      { label: t('ppt.hotkeyPasteAsText'), value: 'Ctrl + Shift + V' },
      { label: t('ppt.hotkeyQuickCopyPaste'), value: 'Ctrl + D' },
      { label: t('ppt.hotkeySelectAll'), value: 'Ctrl + A' },
      { label: t('ppt.hotkeyUndo'), value: 'Ctrl + Z' },
      { label: t('ppt.hotkeyRedo'), value: 'Ctrl + Y' },
      { label: t('ppt.hotkeyDelete'), value: 'Delete / Backspace' },
      { label: t('ppt.hotkeyMultipleSelect'), value: '按住 Ctrl 或 Shift' },
      { label: t('ppt.hotkeyOpenSearchReplace'), value: 'Ctrl + F' },
      { label: t('ppt.hotkeyPrint'), value: 'Ctrl + P' },
      { label: t('ppt.hotkeyCloseDialog'), value: 'ESC' },
    ],
  },
  {
    type: t('ppt.hotkeySlideshow'),
    children: [
      { label: t('ppt.hotkeyStartFromBeginning'), value: 'F6' },
      { label: t('ppt.hotkeyStartFromCurrent'), value: 'Shift + F6' },
      { label: t('ppt.hotkeyPreviousPage'), value: '↑ / ← / PgUp' },
      { label: t('ppt.hotkeyNextPage'), value: '↓ / → / PgDown' },
      { label: t('ppt.hotkeyNextPage'), value: 'Enter / Space' },
      { label: t('ppt.hotkeyExitSlideshow'), value: 'ESC' },
    ],
  },
  {
    type: t('ppt.hotkeySlideEdit'),
    children: [
      { label: t('ppt.hotkeyNewSlide'), value: 'Enter' },
      { label: t('ppt.hotkeyMoveCanvas'), value: 'Space + 鼠标拖拽' },
      { label: t('ppt.hotkeyZoomCanvas'), value: 'Ctrl + 鼠标滚轮' },
      { label: t('ppt.hotkeyZoomIn'), value: 'Ctrl + =' },
      { label: t('ppt.hotkeyZoomOut'), value: 'Ctrl + -' },
      { label: t('ppt.hotkeyFitScreen'), value: 'Ctrl + 0' },
      { label: t('ppt.hotkeyPreviousPageNoSelection'), value: '↑' },
      { label: t('ppt.hotkeyNextPageNoSelection'), value: '↓' },
      { label: t('ppt.hotkeyPreviousPageScroll'), value: '鼠标上滚 / PgUp' },
      { label: t('ppt.hotkeyNextPageScroll'), value: '鼠标下滚 / PgDown' },
      { label: t('ppt.hotkeyQuickText'), value: '双击空白处 / T' },
      { label: t('ppt.hotkeyQuickRectangle'), value: 'R' },
      { label: t('ppt.hotkeyQuickCircle'), value: 'O' },
      { label: t('ppt.hotkeyQuickLine'), value: 'L' },
      { label: t('ppt.hotkeyExitDrawing'), value: '鼠标右键' },
    ],
  },
  {
    type: t('ppt.hotkeyElementOperation'),
    children: [
      { label: t('ppt.hotkeyMove'), value: '↑ / ← / ↓ / →' },
      { label: t('ppt.hotkeyLock'), value: 'Ctrl + L' },
      { label: t('ppt.hotkeyGroup'), value: 'Ctrl + G' },
      { label: t('ppt.hotkeyUngroup'), value: 'Ctrl + Shift + G' },
      { label: t('ppt.hotkeyBringToFront'), value: 'Alt + F' },
      { label: t('ppt.hotkeyBringToBack'), value: 'Alt + B' },
      { label: t('ppt.hotkeyLockRatio'), value: '按住 Ctrl 或 Shift' },
      { label: t('ppt.hotkeyCreateStraightLine'), value: '按住 Ctrl 或 Shift' },
      { label: t('ppt.hotkeyToggleFocus'), value: 'Tab' },
      { label: t('ppt.hotkeyConfirmCrop'), value: 'Enter' },
      { label: t('ppt.hotkeyFinishDrawing'), value: 'Enter' },
    ],
  },
  {
    type: t('ppt.hotkeyTableEdit'),
    children: [
      { label: t('ppt.hotkeyNextCell'), value: 'Tab' },
      { label: t('ppt.hotkeyMoveFocus'), value: '↑ / ← / ↓ / →' },
      { label: t('ppt.hotkeyInsertRowAbove'), value: 'Ctrl + ↑' },
      { label: t('ppt.hotkeyInsertRowBelow'), value: 'Ctrl + ↓' },
      { label: t('ppt.hotkeyInsertColumnLeft'), value: 'Ctrl + ←' },
      { label: t('ppt.hotkeyInsertColumnRight'), value: 'Ctrl + →' },
    ],
  },
  {
    type: t('ppt.hotkeyChartEdit'),
    children: [
      { label: t('ppt.hotkeyNextRow'), value: 'Enter' },
    ],
  },
  {
    type: t('ppt.hotkeyTextEdit'),
    children: [
      { label: t('ppt.hotkeyBold'), value: 'Ctrl + B' },
      { label: t('ppt.hotkeyItalic'), value: 'Ctrl + I' },
      { label: t('ppt.hotkeyUnderline'), value: 'Ctrl + U' },
      { label: t('ppt.hotkeyInlineCode'), value: 'Ctrl + E' },
      { label: t('ppt.hotkeySubscript'), value: `Ctrl + '` },
      { label: t('ppt.hotkeySelectParagraph'), value: `ESC` },
    ],
  },
]